server:
  port: 10000

spring:
  datasource:
    url: '${postgres_url}'
    username: '${postgres_username}'
    password: '${postgres_password}'
    name: 'local'
  #    initialization-mode: always
  #    initialize: true

  jpa:
    show-sql: True
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
